name: Github Package

on:
  workflow_dispatch:

jobs:
     
   publish:
    runs-on: ubuntu-latest
#    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                  "id": "github",
                  "url": "https://maven.pkg.github.com/mahabaleshwars/GithubPackages"
              }
            ]
          servers: >
            [
              {
                "id":"github",
                "username":"mahabaleshwars",
                "password":"${{ secrets.REPO_TOKEN }}"
              }
            ]
      - name: Publish package
        run: mvn --batch-mode -e -X deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
